### ISSUE TITLE
Update readme with firebase instructions

### ISSUE THREAD

**Issue by nityanandagohain** [nityanandagohain/in-time#18]
Update the readme with instructions to create firebase application and add google-services.json file in the android folder

**Comment by InfiniteVerma** [comment]
Hi. I would like to work on this issue. GSSOC 2019 participant.

**Comment by InfiniteVerma** [comment]
Do I add the 'add remote upstream' step in setup?

**Comment by nityanandagohain** [comment]
@InfiniteVerma yes you can add that.
