### ISSUE TITLE
create a login page

### ISSUE THREAD

**Issue by nityanandagohain** [nityanandagohain/in-time#2]

**Comment by jashasweejena** [comment]
I would like to work on this. 🙂

**Comment by nityanandagohain** [comment]
Sure add firebase google sign in in the login page. Also join the glitter channel https://gitter.im/in_time/Lobby

**Comment by jashasweejena** [comment]
> Sure add firebase google sign in in the login page. Also join the glitter channel https://gitter.im/in_time/Lobby

Okay, sure !

**Comment by AjaySharvesh3** [comment]
Hi @jashasweejena  Is this issue is done? If not hall I claim this issue?

**Comment by Starcode71Ooze** [comment]
I would like to work on this issue !! 
Is their anything that you want to suggest in particular??
