### ISSUE TITLE
Add a loader.

### ISSUE THREAD

**Issue by nityanandagohain** [nityanandagohain/in-time#21]
Design a loader that will be displayed when the user clicks on Log in or Sign Up.

**Comment by knightcube** [comment]
I am working on this

**Comment by nityanandagohain** [comment]
okay.

**Comment by knightcube** [comment]
Designing is done. How do I add the functionality to show it as soon as the Login Button is clicked
![ezgif-2-b48b68cc55c2](https://user-images.githubusercontent.com/22871961/50203850-dc6bd200-0388-11e9-8e03-810c4221bb1e.gif)

**Comment by knightcube** [comment]
I tried but sort of stuck. I will make a PR. Kindly tell me how I could go ahead.

**Comment by nityanandagohain** [comment]
I will give you a sample code in gitter channel to help you with that then you can implement it.

**Comment by knightcube** [comment]
That would be a great help. Thanks
