### ISSUE TITLE
update readme.

### ISSUE THREAD

**Issue by nityanandagohain** [nityanandagohain/in-time#30]
remove the todos, add badges, and add a demo gif.

**Comment by nityanandagohain** [comment]
Leave badges, for now, make a gif of the application running.

**Comment by Bhavnaharitsa** [comment]
Done, sending a pr

**Comment by Kvaibhav01** [comment]
@nityanandagohain can I work on this issue? Also, please add the difficulty level tag for this issue.

**Comment by nityanandagohain** [comment]
@Kvaibhav01 sure but I guess there is not much to update on the readme right now and there is already one PR for readme.

**Comment by Kvaibhav01** [comment]
@nityanandagohain but that PR doesn't add todos, badges and a demo gif as you said in this issue.

**Comment by nityanandagohain** [comment]
It was an old issue I didn't properly check it sorry about that.
