### ISSUE TITLE
Improve design of enterTimeTable.dart

### ISSUE THREAD

**Issue by nityanandagohain** [nityanandagohain/in-time#52]
The design of enterTimeTable.dart is to basic. Improve it's design.

**Comment by Kvaibhav01** [comment]
Please assign this issue to me.

**Comment by nityanandagohain** [comment]
Yes, go ahead.

**Comment by Kvaibhav01** [comment]
Do you have any design mockup/wireframe for this? Else, I'll create my own.

**Comment by nityanandagohain** [comment]
Go ahead create your own.
