### ISSUE TITLE
Create a page to enter time table

### ISSUE THREAD

**Issue by nityanandagohain** [nityanandagohain/in-time#9]
So there will be a dropdown where the user can select the day(Ex monday. tuesday)
Add time interval and for each time interval a corresponding class and no of classes missed(initially zero).

**Comment by Bhavnaharitsa** [comment]
Can I work on this issue ?

**Comment by Bhavnaharitsa** [comment]
Okay,sure !!   :)
But, if he isn't ready, I sure will :D
